# Generated by Django 3.2.5 on 2021-07-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('movies', '0001_initial'), ('movies', '0002_alter_movie_vote_average'), ('movies', '0003_alter_movie_overview'), ('movies', '0004_alter_movie_vote_average'), ('movies', '0005_movie_url'), ('movies', '0006_alter_movie_url'), ('movies', '0007_rename_url_movie_mov_url'), ('movies', '0008_auto_20210715_1409'), ('movies', '0009_alter_keyword_movies')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.BigIntegerField(default=-1)),
                ('title', models.CharField(max_length=200)),
                ('match_reason', models.CharField(max_length=50)),
                ('tagline', models.CharField(default='None', max_length=500)),
                ('overview', models.CharField(default='None', max_length=1500)),
                ('vote_average', models.DecimalField(decimal_places=1, default=-1.0, max_digits=3)),
                ('mov_url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('movies', models.ManyToManyField(related_name='keywords', to='movies.Movie')),
            ],
        ),
    ]
