# Generated by Django 3.2.5 on 2021-07-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.BigIntegerField(default=-1)),
                ('title', models.CharField(max_length=200)),
                ('match_reason', models.CharField(max_length=50)),
                ('tagline', models.CharField(max_length=500)),
                ('overview', models.CharField(max_length=1000)),
                ('vote_average', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('movies', models.ManyToManyField(to='movies.Movie')),
            ],
        ),
    ]
