# Generated by Django 3.2.5 on 2021-07-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_vote_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.URLField(default='https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'),
            preserve_default=False,
        ),
    ]
