# Generated by Django 3.2.5 on 2021-07-14 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='url',
            new_name='mov_url',
        ),
    ]
