# Generated by Django 3.2.5 on 2021-07-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_rename_url_movie_mov_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.CharField(default='None', max_length=1500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
