# Generated by Django 3.2.5 on 2021-07-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20210715_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='movies',
            field=models.ManyToManyField(related_name='keywords', to='movies.Movie'),
        ),
    ]
